# Generated by Django 3.1.4 on 2021-01-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20210113_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Name',
            new_name='name',
        ),
    ]
